version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippets
    volumes:
      -  ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


